default_velocity_scaling_factor: 0.1
default_acceleration_scaling_factor: 0.1

# Limits gotten from here: https://github.com/agilexrobotics/scout_ros/blob/01e07881cdc566c3a657e288c59a75577992d13e/scout_base/include/scout_base/scout_params.hpp#L27 :
#         // from user manual v1.2.8 P18
#         // max linear velocity: 1.5 m/s
#         // max angular velocity: 0.7853 rad/s
#         static constexpr double max_linear_speed = 1.5;     // in m/s
#         static constexpr double max_angular_speed = 0.7853; // in rad/s
#         static constexpr double max_speed_cmd = 10.0;       // in rad/s
# Assuminng these are lin/ang velocities for the chassis, then:
# max_wheel_speed = (v + w * track/2) / wheel_radius
#                  = (1.5 + 0.7853 * 0.58306/2) / 0.160
#                  = (1.5 + 0.2289) / 0.160
#                  ~= 10.8 rad/s
# (where v is linear velocity and w is angular velocity)
joint_limits:
  front_right_wheel:
    has_velocity_limits: true
    max_velocity: 10
    has_acceleration_limits: false
    max_acceleration: 0
  front_left_wheel:
    has_velocity_limits: true
    max_velocity: 10
    has_acceleration_limits: false
    max_acceleration: 0
  rear_left_wheel:
    has_velocity_limits: true
    max_velocity: 10
    has_acceleration_limits: false
    max_acceleration: 0
  rear_right_wheel:
    has_velocity_limits: true
    max_velocity: 10
    has_acceleration_limits: false
    max_acceleration: 0
